import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Maps the prototype's icon keys (icons.js / `data-lucide`) to Lucide glyphs.
/// Keys are used by data (notifications, drawer destinations) so screens never
/// depend on icon constants directly. Weight 500 (stroke ≈2.5) — the CricEco
/// reference's outline weight; same glyphs as the default set.
abstract final class CeIcons {
  static const Map<String, IconData> byKey = {
    'arrow-left': LucideIcons.arrowLeft500,
    'arrow-right': LucideIcons.arrowRight500,
    'arrow-up-right': LucideIcons.arrowUpRight500,
    'arrow-right-to-line': LucideIcons.arrowRightToLine500,
    'chevron-down': LucideIcons.chevronDown500,
    'chevron-up': LucideIcons.chevronUp500,
    'chevron-left': LucideIcons.chevronLeft500,
    'chevron-right': LucideIcons.chevronRight500,
    'check': LucideIcons.check500,
    'check-circle': LucideIcons.circleCheck500,
    'x': LucideIcons.x500,
    'x-circle': LucideIcons.circleX500,
    'plus': LucideIcons.plus500,
    'plus-circle': LucideIcons.circlePlus500,
    'menu': LucideIcons.menu500,
    'more-vertical': LucideIcons.ellipsisVertical500,
    'more-horizontal': LucideIcons.ellipsis500,
    'info': LucideIcons.info500,
    'user': LucideIcons.user500,
    'user-plus': LucideIcons.userPlus500,
    'calendar-check': LucideIcons.calendarCheck500,
    'users': LucideIcons.users500,
    'calendar': LucideIcons.calendar500,
    'clock': LucideIcons.clock500,
    'timer': LucideIcons.timer500,
    'hourglass': LucideIcons.hourglass500,
    'map-pin': LucideIcons.mapPin500,
    'home': LucideIcons.house500,
    'building-2': LucideIcons.building2500,
    'shield': LucideIcons.shield500,
    'trophy': LucideIcons.trophy500,
    'award': LucideIcons.award500,
    'star': LucideIcons.star500,
    'crown': LucideIcons.crown500,
    'flame': LucideIcons.flame500,
    'zap': LucideIcons.zap500,
    'bell': LucideIcons.bell500,
    'lock': LucideIcons.lock500,
    'key': LucideIcons.key500,
    'eye': LucideIcons.eye500,
    'eye-off': LucideIcons.eyeOff500,
    'search': LucideIcons.search500,
    'mail': LucideIcons.mail500,
    'phone': LucideIcons.phone500,
    'camera': LucideIcons.camera500,
    'image': LucideIcons.image500,
    'trash-2': LucideIcons.trash2500,
    'file-text': LucideIcons.fileText500,
    'clipboard-list': LucideIcons.clipboardList500,
    'edit-3': LucideIcons.penLine500,
    'tag': LucideIcons.tag500,
    'bar-chart': LucideIcons.chartNoAxesColumn500,
    'trending-up': LucideIcons.trendingUp500,
    'target': LucideIcons.target500,
    'circle-dot': LucideIcons.circleDot500,
    'minus': LucideIcons.minus500,
    'circle': LucideIcons.circle500,
    'flag': LucideIcons.flag500,
    'hand': LucideIcons.hand500,
    'swords': LucideIcons.swords500,
    'credit-card': LucideIcons.creditCard500,
    'banknote': LucideIcons.banknote500,
    'wallet': LucideIcons.wallet500,
    'hash': LucideIcons.hash500,
    'radio': LucideIcons.radio500,
    'activity': LucideIcons.activity500,
    'user-check': LucideIcons.userCheck500,
    'footprints': LucideIcons.footprints500,
    'lightbulb': LucideIcons.lightbulb500,
    'megaphone': LucideIcons.megaphone500,
    'share-2': LucideIcons.share2500,
    'sparkles': LucideIcons.sparkles500,
    'rocket': LucideIcons.rocket500,
    'snowflake': LucideIcons.snowflake500,
    'wind': LucideIcons.wind500,
    'sun': LucideIcons.sun500,
    'droplets': LucideIcons.droplets500,
    'coffee': LucideIcons.coffee500,
    'store': LucideIcons.store500,
    'car': LucideIcons.car500,
    'wrench': LucideIcons.wrench500,
    'sliders': LucideIcons.slidersVertical500,
    'smartphone': LucideIcons.smartphone500,
    'link': LucideIcons.link500,
    'power': LucideIcons.power500,
    'fast-forward': LucideIcons.fastForward500,
    'corner-up-left': LucideIcons.cornerUpLeft500,
    'party-popper': LucideIcons.partyPopper500,
    'repeat': LucideIcons.repeat500,
    'flask-conical': LucideIcons.flaskConical500,
  };

  static IconData of(String key) => byKey[key] ?? LucideIcons.circle500;
}
