import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Maps the prototype's icon keys (icons.js / `data-lucide`) to Lucide glyphs.
/// Keys are used by data (notifications, drawer destinations) so screens never
/// depend on icon constants directly.
abstract final class CeIcons {
  static const Map<String, IconData> byKey = {
    'arrow-left': LucideIcons.arrowLeft,
    'arrow-right': LucideIcons.arrowRight,
    'arrow-up-right': LucideIcons.arrowUpRight,
    'arrow-right-to-line': LucideIcons.arrowRightToLine,
    'chevron-down': LucideIcons.chevronDown,
    'chevron-up': LucideIcons.chevronUp,
    'chevron-left': LucideIcons.chevronLeft,
    'chevron-right': LucideIcons.chevronRight,
    'check': LucideIcons.check,
    'check-circle': LucideIcons.circleCheck,
    'x': LucideIcons.x,
    'x-circle': LucideIcons.circleX,
    'plus': LucideIcons.plus,
    'plus-circle': LucideIcons.circlePlus,
    'menu': LucideIcons.menu,
    'more-vertical': LucideIcons.ellipsisVertical,
    'more-horizontal': LucideIcons.ellipsis,
    'info': LucideIcons.info,
    'user': LucideIcons.user,
    'user-plus': LucideIcons.userPlus,
    'users': LucideIcons.users,
    'calendar': LucideIcons.calendar,
    'clock': LucideIcons.clock,
    'timer': LucideIcons.timer,
    'hourglass': LucideIcons.hourglass,
    'map-pin': LucideIcons.mapPin,
    'home': LucideIcons.house,
    'building-2': LucideIcons.building2,
    'shield': LucideIcons.shield,
    'trophy': LucideIcons.trophy,
    'award': LucideIcons.award,
    'star': LucideIcons.star,
    'crown': LucideIcons.crown,
    'flame': LucideIcons.flame,
    'zap': LucideIcons.zap,
    'bell': LucideIcons.bell,
    'lock': LucideIcons.lock,
    'key': LucideIcons.key,
    'eye': LucideIcons.eye,
    'eye-off': LucideIcons.eyeOff,
    'search': LucideIcons.search,
    'mail': LucideIcons.mail,
    'phone': LucideIcons.phone,
    'camera': LucideIcons.camera,
    'file-text': LucideIcons.fileText,
    'clipboard-list': LucideIcons.clipboardList,
    'edit-3': LucideIcons.penLine,
    'tag': LucideIcons.tag,
    'bar-chart': LucideIcons.chartNoAxesColumn,
    'trending-up': LucideIcons.trendingUp,
    'target': LucideIcons.target,
    'circle-dot': LucideIcons.circleDot,
    'minus': LucideIcons.minus,
    'circle': LucideIcons.circle,
    'flag': LucideIcons.flag,
    'hand': LucideIcons.hand,
    'swords': LucideIcons.swords,
    'credit-card': LucideIcons.creditCard,
    'banknote': LucideIcons.banknote,
    'wallet': LucideIcons.wallet,
    'hash': LucideIcons.hash,
    'radio': LucideIcons.radio,
    'activity': LucideIcons.activity,
    'footprints': LucideIcons.footprints,
    'lightbulb': LucideIcons.lightbulb,
    'megaphone': LucideIcons.megaphone,
    'sparkles': LucideIcons.sparkles,
    'rocket': LucideIcons.rocket,
    'snowflake': LucideIcons.snowflake,
    'wind': LucideIcons.wind,
    'sun': LucideIcons.sun,
    'droplets': LucideIcons.droplets,
    'coffee': LucideIcons.coffee,
    'store': LucideIcons.store,
    'car': LucideIcons.car,
    'wrench': LucideIcons.wrench,
    'sliders': LucideIcons.slidersVertical,
    'smartphone': LucideIcons.smartphone,
    'link': LucideIcons.link,
    'power': LucideIcons.power,
    'fast-forward': LucideIcons.fastForward,
    'corner-up-left': LucideIcons.cornerUpLeft,
    'party-popper': LucideIcons.partyPopper,
    'repeat': LucideIcons.repeat,
    'flask-conical': LucideIcons.flaskConical,
  };

  static IconData of(String key) => byKey[key] ?? LucideIcons.circle;
}
